### ISSUE TITLE
Shows cors error

### ISSUE THREAD

**Issue by santhoshkumarch** [viking2917/ionic-epub-reader#5]
Access to fetch at 'https://standardebooks.org/ebooks/robert-louis-stevenson/treasure-island/milo-winter/dist/robert-louis-stevenson_treasure-island.epub' from origin 'https://s3-us-west-2.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
angularEpubReader.js:1447 GET https://standardebooks.org/ebooks/robert-louis-stevenson/treasure-island/milo-winter/dist/robert-louis-stevenson_treasure-island.epub net::ERR_FAILED
controller @ angularEpubReader.js:1447
invoke @ ionic.bundle.js:18000
$controllerInit @ ionic.bundle.js:23402
nodeLinkFn @ ionic.bundle.js:22340
(anonymous) @ ionic.bundle.js:22737
processQueue @ ionic.bundle.js:29132
(anonymous) @ ionic.bundle.js:29148
$eval @ ionic.bundle.js:30400
$digest @ ionic.bundle.js:30216
$apply @ ionic.bundle.js:30508
(anonymous) @ ionic.bundle.js:65428
defaultHandlerWrapper @ ionic.bundle.js:16792
eventHandler @ ionic.bundle.js:16780
triggerMouseEvent @ ionic.bundle.js:2953
tapClick @ ionic.bundle.js:2942
tapTouchEnd @ ionic.bundle.js:3069
angularEpubReader.js:1400 error loading book TypeError: Failed to fetch
index.html#/tab/dash:1 Access to XMLHttpRequest at 'https://standardebooks.org/ebooks/robert-louis-stevenson/treasure-island/milo-winter/dist/robert-louis-stevenson_treasure-island.epub' from origin 'https://s3-us-west-2.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
epub.v0.3.66.js:3492 GET https://standardebooks.org/ebooks/robert-louis-stevenson/treasure-island/milo-winter/dist/robert-louis-stevenson_treasure-island.epub net::ERR_FAILED

**Comment by viking2917** [comment]
Thank you @santhoshkumarch for noticing that and getting in touch. Looks like Standard Ebooks changed their cors policy at some point. I've updated the app to use a local version of Treasure Island in case you want to try it out. Or the last menu item lets you upload your own epub.

Thanks!

**Comment by viking2917** [comment]
Actually turns out even simpler. Not a CORs error: simply that the location of the ePub had moved, but instead of a 404 it throws a CORs error. Fixing the location fixes the issue.
